---
abstract: 'Find and markup URLs in plain text'
author:
  - 'Tomáš Znamenáček, zoul@fleuron.cz'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-FindLinks
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
